# Generated by Django 5.1.6 on 2025-03-16 07:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0006_remove_store_owner'),
        ('main', '0010_inventoryitem_expire_date_inventoryitem_lot_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refund_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='환불일시')),
                ('customer_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='고객전화번호')),
                ('reason', models.TextField(blank=True, null=True, verbose_name='환불사유')),
                ('status', models.CharField(choices=[('PENDING', '처리 중'), ('APPROVED', '승인됨'), ('COMPLETED', '완료됨'), ('REJECTED', '거부됨')], default='PENDING', max_length=10, verbose_name='상태')),
                ('refund_method', models.CharField(choices=[('CARD', '카드'), ('BANK', '계좌이체'), ('POINT', '포인트')], default='CASH', max_length=10, verbose_name='환불방법')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='비고')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('order_number', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.workitem', verbose_name='주문번호')),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.store', verbose_name='매장')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='처리자')),
            ],
            options={
                'verbose_name': '환불',
                'verbose_name_plural': '환불 목록',
            },
        ),
        migrations.CreateModel(
            name='RefundItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='수량')),
                ('unit_price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='환불 단가')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.product', verbose_name='상품')),
                ('refund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refund_items', to='refund.refund', verbose_name='환불')),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.store', verbose_name='매장')),
            ],
            options={
                'verbose_name': '환불 상품',
                'verbose_name_plural': '환불 상품 목록',
            },
        ),
        migrations.AddIndex(
            model_name='refund',
            index=models.Index(fields=['store', 'refund_date'], name='idx_refund_date'),
        ),
        migrations.AddIndex(
            model_name='refund',
            index=models.Index(fields=['status'], name='idx_refund_status'),
        ),
        migrations.AddIndex(
            model_name='refund',
            index=models.Index(fields=['order_number'], name='idx_refund_order'),
        ),
        migrations.AddIndex(
            model_name='refunditem',
            index=models.Index(fields=['refund', 'product'], name='idx_refund_product'),
        ),
    ]
