# Generated by Django 5.1.6 on 2025-03-06 23:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='매장명')),
                ('business_number', models.CharField(max_length=20, verbose_name='사업자번호')),
                ('phone_number', models.CharField(max_length=15, verbose_name='전화번호')),
                ('address', models.TextField(verbose_name='주소')),
                ('website', models.URLField(blank=True, null=True, verbose_name='웹사이트')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stores', to=settings.AUTH_USER_MODEL, verbose_name='매장 대표')),
            ],
            options={
                'verbose_name': '매장',
                'verbose_name_plural': '매장 목록',
            },
        ),
    ]
