# Generated by Django 5.1.6 on 2025-03-06 23:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_store'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='owner',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_store_owner',
            field=models.BooleanField(default=False, verbose_name='매장 소유자 여부'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='accounts.store', verbose_name='매장'),
        ),
    ]
