# Generated by Django 5.1.6 on 2025-03-08 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_userprofile_store_alter_store_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='owner',
        ),
    ]
