# Generated by Django 5.1.6 on 2025-03-06 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workitem',
            name='customer_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='고객전화번호'),
        ),
    ]
