# Generated by Django 5.1.6 on 2025-03-06 23:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_store'),
        ('main', '0002_workitem_customer_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.store', verbose_name='매장'),
        ),
        migrations.AddField(
            model_name='product',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.store', verbose_name='매장'),
        ),
        migrations.AddField(
            model_name='workitem',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.store', verbose_name='매장'),
        ),
    ]
