# Generated by Django 5.1.6 on 2025-03-09 01:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_store_owner'),
        ('main', '0004_product_barcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='브랜드명')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='brands/', verbose_name='브랜드 로고')),
                ('description', models.TextField(blank=True, null=True, verbose_name='브랜드 설명')),
                ('website', models.URLField(blank=True, null=True, verbose_name='웹사이트')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.store', verbose_name='매장')),
            ],
            options={
                'verbose_name': '브랜드',
                'verbose_name_plural': '브랜드',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='main.brand', verbose_name='브랜드'),
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='공급처명')),
                ('business_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='사업자번호')),
                ('contact_info', models.CharField(blank=True, max_length=200, null=True, verbose_name='연락처')),
                ('address', models.TextField(blank=True, null=True, verbose_name='주소')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='이메일')),
                ('website', models.URLField(blank=True, null=True, verbose_name='웹사이트')),
                ('contact_person', models.CharField(blank=True, max_length=100, null=True, verbose_name='담당자')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.store', verbose_name='매장')),
            ],
            options={
                'verbose_name': '공급처',
                'verbose_name_plural': '공급처',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='brand',
            name='supplier',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='brands', to='main.supplier', verbose_name='공급처'),
        ),
    ]
