# Generated by Django 5.1.6 on 2025-03-09 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_brand_product_brand_supplier_brand_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='workitem',
            name='work_class',
            field=models.CharField(choices=[('WORK', '작업'), ('SALE', '판매'), ('ONLINE', '온라인'), ('KIOSK', '키오스크')], default='WORK', max_length=10, verbose_name='작업구분'),
        ),
    ]
