# Generated by Django 5.1.6 on 2025-03-10 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_store_owner'),
        ('main', '0006_workitem_work_class'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': '상품', 'verbose_name_plural': '상품'},
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['store', 'barcode'], name='idx_store_barcode'),
        ),
    ]
