# Generated by Django 5.1.6 on 2025-03-10 09:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_store_owner'),
        ('main', '0007_alter_product_options_product_idx_store_barcode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workitem',
            options={'verbose_name': '작업', 'verbose_name_plural': '작업목록'},
        ),
        migrations.AddIndex(
            model_name='workitem',
            index=models.Index(fields=['work_class', 'store', 'date_time'], name='idx_list1'),
        ),
        migrations.AddIndex(
            model_name='workitem',
            index=models.Index(fields=['work_class', 'store', 'payment_method'], name='idx_list2'),
        ),
    ]
