# Generated by Django 5.1.6 on 2025-03-10 12:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_store_owner'),
        ('main', '0008_alter_workitem_options_workitem_idx_list1_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='입고 수량')),
                ('purchase_price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='매입가')),
            ],
            options={
                'verbose_name': '입고 상품',
                'verbose_name_plural': '입고 상품 목록',
            },
        ),
        migrations.CreateModel(
            name='ProductInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory_date', models.DateTimeField(verbose_name='입고일시')),
                ('reference_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='참조번호')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='비고')),
                ('is_confirmed', models.BooleanField(default=False, verbose_name='확정 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'verbose_name': '상품 입고',
                'verbose_name_plural': '상품 입고 목록',
                'ordering': ['-inventory_date'],
            },
        ),
        migrations.AlterModelOptions(
            name='material',
            options={'verbose_name': '재료', 'verbose_name_plural': '재료'},
        ),
        migrations.AddIndex(
            model_name='material',
            index=models.Index(fields=['work_item', 'product'], name='idx_material_product'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.product', verbose_name='상품'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.store', verbose_name='매장'),
        ),
        migrations.AddField(
            model_name='productinventory',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.store', verbose_name='매장'),
        ),
        migrations.AddField(
            model_name='productinventory',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_inventories', to='main.supplier', verbose_name='공급업체'),
        ),
        migrations.AddField(
            model_name='productinventory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='담당자'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='inventory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='main.productinventory', verbose_name='입고'),
        ),
        migrations.AddIndex(
            model_name='productinventory',
            index=models.Index(fields=['store', 'inventory_date'], name='idx_inventory_date'),
        ),
        migrations.AddIndex(
            model_name='productinventory',
            index=models.Index(fields=['supplier'], name='idx_inventory_supplier'),
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['inventory', 'product'], name='idx_inventory_product'),
        ),
    ]
