# Generated by Django 5.1.6 on 2025-03-10 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_inventoryitem_productinventory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='expire_date',
            field=models.DateField(blank=True, null=True, verbose_name='유통기한'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='lot_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='로트번호'),
        ),
    ]
